class Starfield{constructor(){this.canvas=document.createElement('canvas');this.canvas.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;pointer-events:none;z-index:0;';document.body.prepend(this.canvas);this.ctx=this.canvas.getContext('2d');this.stars=[];this.nebulas=[];this.mouse={x:0,y:0,tx:0,ty:0};this.t=0;this.resize();this.create();window.addEventListener('resize',()=>{this.resize();this.create();});window.addEventListener('mousemove',e=>{this.mouse.tx=e.clientX;this.mouse.ty=e.clientY;});this.mouse.x=window.innerWidth/2;this.mouse.y=window.innerHeight/2;this.mouse.tx=this.mouse.x;this.mouse.ty=this.mouse.y;requestAnimationFrame(()=>this.draw());}
resize(){this.w=window.innerWidth;this.h=window.innerHeight;this.canvas.width=this.w*devicePixelRatio;this.canvas.height=this.h*devicePixelRatio;this.ctx.scale(devicePixelRatio,devicePixelRatio);}
create(){this.stars=Array.from({length:200},()=>({x:Math.random()*this.w,y:Math.random()*this.h,r:Math.random()*1.5+0.3,base:Math.random()*0.5+0.3,speed:Math.random()*0.02+0.005,phase:Math.random()*Math.PI*2,par:Math.random()*0.03+0.005}));this.nebulas=Array.from({length:5},(_,i)=>({x:Math.random()*this.w,y:Math.random()*this.h,r:Math.random()*300+200,color:i%2===0?'rgba(108,99,255,0.035)':'rgba(79,142,247,0.025)'}));}
draw(){this.ctx.clearRect(0,0,this.w,this.h);this.mouse.x+=(this.mouse.tx-this.mouse.x)*0.06;this.mouse.y+=(this.mouse.ty-this.mouse.y)*0.06;
this.nebulas.forEach(n=>{const g=this.ctx.createRadialGradient(n.x,n.y,0,n.x,n.y,n.r);g.addColorStop(0,n.color);g.addColorStop(1,'rgba(0,0,0,0)');this.ctx.fillStyle=g;this.ctx.beginPath();this.ctx.arc(n.x,n.y,n.r,0,Math.PI*2);this.ctx.fill();});
const mg=this.ctx.createRadialGradient(this.mouse.x,this.mouse.y,0,this.mouse.x,this.mouse.y,400);mg.addColorStop(0,'rgba(108,99,255,0.04)');mg.addColorStop(1,'rgba(0,0,0,0)');this.ctx.fillStyle=mg;this.ctx.beginPath();this.ctx.arc(this.mouse.x,this.mouse.y,400,0,Math.PI*2);this.ctx.fill();
this.stars.forEach(s=>{s.phase+=s.speed;const ox=(this.mouse.x-this.w/2)*s.par,oy=(this.mouse.y-this.h/2)*s.par;let rx=(s.x-ox+this.w)%this.w,ry=(s.y-oy+this.h)%this.h;const twinkle=Math.sin(s.phase)*0.25;let op=s.base+twinkle,r=s.r,color='#ffffff';const dx=this.mouse.x-rx,dy=this.mouse.y-ry,dist=Math.sqrt(dx*dx+dy*dy);if(dist<180){const f=(180-dist)/180;op+=f*0.4;r+=f*0.3;color='#d9d6ff';}op=Math.max(0.1,Math.min(1,op));this.ctx.globalAlpha=op;this.ctx.fillStyle=color;this.ctx.beginPath();this.ctx.arc(rx,ry,r,0,Math.PI*2);this.ctx.fill();});
this.ctx.globalAlpha=1;requestAnimationFrame(()=>this.draw());}
}
export default Starfield;
